name: fros-x64  #CI项目名

on: #触发条件
  workflow_dispatch:  #手动编译

env:
  OWRT_TARGET: fros-x64  #项目平台
  OWRT_NAME: fros-x64 #默认主机名
  OWRT_THEME: design  #默认主题
  OWRT_IP: 192.168.2.1  #默认IP地址
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LEDE_URL: https://github.com/openfros/fros.git
  LIST_URL: https://raw.githubusercontent.com/herofence/r2s/master/Depends.txt

permissions: write-all

jobs: #执行项目
  build_openwrt:
    name: fros-x64固件云编译
    runs-on: ubuntu-latest
    steps: #步骤
      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(curl -sfL $LIST_URL | sed -n "1{s/\r$//;p;q}")
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(curl -sfL $LIST_URL | sed -n "2{s/\r$//;p;q}")
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(curl -sfL $LIST_URL | sed -n "3{s/\r$//;p;q}")
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          sudo -E apt -yqq autoclean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: 检查项目
        uses: actions/checkout@v3

      - name: 检查脚本
        run: |
          cd ./Scripts

          chmod +x ./*.sh
          dos2unix ./*.sh

      - name: 复制LEDE源码
        run: |
          git clone --depth=1 --single-branch $LEDE_URL

      - name: 更新Feeds源
        run: |
          cd ./lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 自定义脚本
        run: |
          cd ./lede
          $GITHUB_WORKSPACE/Scripts/Settings.sh

          cd ./package
          $GITHUB_WORKSPACE/Scripts/Plugins.sh

      - name: 自定义设置
        run: |
          cd ./lede

          rm -rf ./tmp && rm -rf ./.config*
          cat $GITHUB_WORKSPACE/Config/$OWRT_TARGET.txt $GITHUB_WORKSPACE/Config/General.txt >> .config
          
          $GITHUB_WORKSPACE/Scripts/Extras.sh
          
          make defconfig
      - name: 清理工具链
        run: |
          cd ./lede

          make dirclean
      - name: 下载软件包
        run: |
          cd ./lede

          make download -j$(nproc)

      - name: 编译固件
        run: |
          cd ./lede

          make -j$(nproc) || make -j1 V=s

          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./build_dir
          echo "======================="
          du -h --max-depth=1 ./bin
          echo "======================="

      - name: 编译软件包
        run: |
          export OWRT_TYPE=$(sed -n "1{s/^#//;s/\r$//;p;q}" $GITHUB_WORKSPACE/Config/$OWRT_TARGET.txt)
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")

          echo "OWRT_TARGET=$OWRT_TARGET" >> $GITHUB_ENV
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          echo "OWRT_TYPE=$OWRT_TYPE" >> $GITHUB_ENV
          echo "OWRT_IP=$OWRT_IP" >> $GITHUB_ENV

          cd ./lede && mkdir ./upload
          cp -rf $(find ./bin/targets/ -type f -iregex ".*\.\(bin\|iso\|vmdk\|img.gz\)") ./upload/
          cp -rf ./.config ./upload/"$OWRT_TARGET"_Config_"$OWRT_DATE".txt

          cd ./upload
          $GITHUB_WORKSPACE/Scripts/Renames.sh

      - name: 导出固件
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.OWRT_TARGET}}_OWRT_${{env.OWRT_DATE}}
          files: ./lede/upload/*.*
          body: |
            此固件仅有passwall无USB驱动
            设备：${{env.OWRT_TYPE}}
            地址：${{env.OWRT_IP}}
            密码：password

      - name: 删除旧版本
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 4
          delete_tags: true

      - name: 删除旧工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
